PATH:
  TRAIN_PATH: "/home/apie/projects/MTMC2021_ver2/dataset/train"
  VALID_PATH: "/home/apie/projects/MTMC2021_ver2/dataset/validation"
  OUTPUT_PATH: "/home/apie/projects/MTMC2021_ver2/mct_model/checkpoints"

DEVICE:
  TYPE: "cuda"
  GPU: 1

MCT:
  FEATURE_DIM: 2048
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.3
  EPOCHS: 5
  BATCH_SIZE: 16
  RW: True
  WEIGHT: "/home/apie/projects/MTMC2021_ver2/mct_model/checkpoints/None_3.pth"
  