PATH:
  INPUT_PATH: "/home/apie/projects/MTMC2021/dataset/train"
  VALID_PATH: "/home/apie/projects/MTMC2021/dataset/validation"
  OUTPUT_PATH: "/home/apie/projects/MTMC2021/mct_model/checkpoints"

DEVICE:
  TYPE: "cuda"
  GPU: 4

MCT: 
  E_LAYERS: 3
  FEATURE_DIM: 2048
  LEARNING_RATE: 0.0001
  EPOCHS: 100
  BATCH_SIZE: 64
  WEIGHT: "/home/apie/projects/MTMC2021/mct_model/checkpoints/mct_epoch100.pth"