PATH:
  INPUT_PATH: "/home/apie/projects/MTMC2021/dataset/train"
  VALID_PATH: "/home/apie/projects/MTMC2021/dataset/validation"
  OUTPUT_PATH: "/home/apie/projects/MTMC2021/mtc_model/checkpoints"

DEVICE:
  TYPE: "cuda"
  GPUS: [4, 5, 6]

MCT: 
  E_LAYERS: 3
  FEATURE_DIM: 2048
  LEARNING_RATE: 0.0001
  EPOCHS: 50
  BATCH_SIZE: 64
  WEIGHT: "/home/apie/projects/MTMC2021/mtc_model/checkpoints/best_model.pth"