PATH:
  INPUT_PATH: "/home/apie/projects/MTMC2021/dataset/train"
  OUTPUT_PATH: "/home/apie/projects/MTMC2021/mtc_model/checkpoints"

DEVICE:
  TYPE: "cuda"
  GPUS: [4, 5, 6]

MCT: 
  E_LAYERS: 3
  FEATURE_DIM: 2048
  LEARNING_RATE: 0.001
  EPOCHS: 10