OUTPUT_ROOT: generate_clusters
DIST_BACKEND: 'nccl'
WORKERS: 4
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  FILE: ObjtrackDataset
  NAME: ObjtrackDataset
  ROOT: '/mnt/cephfs_new_wj/cv/chenmingfei.lasia/TNT_pytorch/data'
  IMG_NUM_PER_GPU: 8
  MEAN: [102.9801, 115.9465, 122.7717]
  STD: [1, 1, 1]
  NUM_CLASSES: 9
TRACKLET:
  WINDOW_lEN: 64
MODEL:
  FILE: tracklet_connectivity
  NAME: TrackletConnectivity
  CONNECTIVITY:
    KERNEL_SIZE: [3, 5, 9, 13]
    FEAT_CHANNELS: [16, 64, 128]
    STACK_NUM: 3
  APPEARANCE:
    EMB_SIZE: 512
    WEIGHTS: '/mnt/ht/students/cmf/TNT_pytorch/work_dirs/facenet_triplet_appearance/2020-03-11-05-18/InceptionResnetV1_epoch001_iter024000_checkpoint.pth'
  RESUME_PATH: '/mnt/ht/students/cmf/TNT_pytorch/work_dirs/trackletpair_connectivity/2020-03-13-02-08/TrackletConnectivity_epoch000_iter008000_checkpoint.pth'
  DETECTION_WEIGHTS: '/mnt/ht/students/cmf/TNT_pytorch/work_dirs/fcos_detector/2020-03-10-05-51/FCOS_epoch012_iter024000_checkpoint.pth'
  BACKBONE:
    PRETRAINED: False
    CONV_BODY: 'R-50-FPN-RETINANET'
    WEIGHTS: ''
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  NECK:
    IN_CHANNELS: [256, 512, 1024, 2048]
    OUT_CHANNELS: 256
    START_LEVEL: 1
    ADD_EXTRA_CONVS: True
    NUM_OUTS: 5
  HEAD:
    IN_CHANNELS: 256
    OUT_CHANNELS: 256
    STACKED_CONVS: 4
    STRIDES: (8, 16, 32, 64, 128)
TEST:
  TEST_SIZE: (352, 1216) # min_size, max_size
  CROP_SZIE: (91, 182)
  NMS_THRESHOLD: 0.6
  SCORE_THRESHOLD: 0.3
  AP_IOU: 0.5
  MAX_PER_IMG: 100
  NMS_PRE: 1000
  # OUT_DIR: 'output'





