OUTPUT_ROOT: facenet_triplet_appearance
DIST_BACKEND: 'nccl'
PI: 'triplet_loss'
WORKERS: 4
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  ROOT: '/mnt/ht/students/cmf/TNT_pytorch/data/crop_data'
  IMG_NUM_PER_GPU: 16
  MEAN: [102.9801, 115.9465, 122.7717]
  STD: [1, 1, 1]
MODEL:
  FILE: inception_resnet_v1
  NAME: InceptionResnetV1
  FEATURE_PATH: 'data/20180402-114759-vggface2-features.pt'
  LOGITS_PATH: 'data/20180402-114759-vggface2-logits.pt'
  RESUME_PATH: 'work_dirs/facenet_triplet_appearance/2020-03-11-05-18/InceptionResnetV1_epoch001_iter024000_checkpoint.pth'
TRAINER:
  FILE: appearanceTrainer
  NAME: appearanceTrainer
TRAIN:
  LR: 0.001
  LR_FACTOR: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_STEPS: [12000, 16000]
  MAX_ITERATIONS: 25000
  OPTIMIZER: sgd
  RESUME: True
  INPUT_MIN: 91
  INPUT_MAX: 182 
  PRINT_FREQ: 200
  SAVE_INTERVAL: 2000
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: False
TEST:
  TEST_SIZE: (91, 182) # min_size, max_size
  OUT_DIR: 'output'





